version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'momentum'
      MYSQL_USER: 'mom'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'

  api:
    depends_on:
      - db
    restart: always
    env_file:
      - env-vars.list
