version: '3.8'

services:
  db:
    platform: linux/x86_64
    volumes:
      - ./scripts/init-db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'momentum'
      MYSQL_USER: 'mom'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'

  api:
    platform: linux/x86_64
    volumes:
      - ./scripts:/app/scripts
      - ./server:/app/server
      - /app/server/node_modules/
    build:
      context: ./server
      dockerfile: dev.Dockerfile

  integration-tests:
    extends: api
    entrypoint: sh -c "npm test"
    environment:
      NODE_ENV: 'test'
