version: '3.8'

services:
  db:
    platform: linux/x86_64
    volumes:
      - ./scripts/init-db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'momentum'
      MYSQL_USER: 'mom'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'

  api:
    platform: linux/x86_64
    volumes:
      - ./scripts:/app/scripts
      - ./server/config:/app/server/config
      - ./server/docs:/app/server/docs
      - ./server/public:/app/server/public
      - ./server/src:/app/server/src
      - ./server/test:/app/server/test
    build:
      context: ./server
      dockerfile: Dockerfile
    entrypoint: sh -c "npm install -g nodemon --unsafe-perm && nodemon server.js"
