version: '3.8'

services:
  db:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql

  api:
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    ports:
      - ${NODE_PORT}:3002
